#**PROJECT-1 PRAKTIKUM FISIKA KOMPUTASI 118**

---
***Currents and Voltages in Resistor Circuits***
---

**KELOMPOK 2 - Fisika B**
1.   Dhinar Hidayath 		       (1306621054)
2.   Khansa Farras Callista	A. (1306621067)
3.   Puspa Zuhrotul Kamilah	   (1306621058)
4.   Salma Mardhiyah     	     (1306621061)



#**GAUSS - NAIVE**

In [ ]:
def gauss_naive(Ab):
    Ab = Ab.astype(float)
    print("\n", "="*22, "PENYELESAIAN DENGAN GAUSS-NAIVE","="*21, "\n")

    for i in range(n):
        if np.fabs(Ab[0, 0]) < 1.0e-10:
            print('Divide by zero detected!\n')
            return
            
        for j in range(i+1, n):
            faktor = Ab[j][i]/Ab[i][i]
            for k in range(n+1):
                Ab[j][k] = Ab[j][k] - faktor * Ab[i][k]
            print("Untuk kolom ke-{} baris ke-{} :".format(i+1, j+1))
            print(Ab, "\n")
        
    # Back Substitution
    x[n-1] = Ab[n-1][n]/Ab[n-1][n-1]
    for i in range(n-2, -1, -1):
        sum = Ab[i][n]
        
        for j in range(i+1, n):
            sum = sum - Ab[i,j] * x[j]
        x[i] = sum/Ab[i][i]

    print("="*77)
    print("\nDidapat Akar Solusi Persamaan \nI1 = {} A\nI2 = {} A\nI3 = {} A\n".format(x[0], x[1], x[-1]))

    stop = timeit.default_timer()
    print('Running Time : ', stop - start, 'detik')
    return 

import numpy as np
import timeit

start = timeit.default_timer()

# Judul Program
print("======= MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE GAUSS NAIVE =======\n")

# Matriks yang digunakan
print("Sistem Persamaan Linear \n-6I1 - 4I2 - 2I3  = 20 \n-4I1 + 18I2 - 8I3 = 0 \n-2I1 - 8I2 + 15I3 = 0")

A = np.array([[6,-4,-2], [-4,18,-8], [-2,-8,15]])
b = np.array([20, 0, 0])
n = len(b)
x = np.zeros(n)
Ab = np.column_stack((A, b))

print(f"\nMatriks A : \n{A}\n\nMatriks b :  \n{np.transpose([b])}")
print(f"\nMaka, matriks untuk [A|b] : \n{Ab}")

# Memanggil fungsi definisi Gauss-Naive
solusi = gauss_naive(Ab)

# SELESAI

======= MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE GAUSS NAIVE =======

Sistem Persamaan Linear 
-6I1 - 4I2 - 2I3  = 20 
-4I1 + 18I2 - 8I3 = 0 
-2I1 - 8I2 + 15I3 = 0

Matriks A : 
[[ 6 -4 -2]
 [-4 18 -8]
 [-2 -8 15]]

Matriks b :  
[[20]
 [ 0]
 [ 0]]

Maka, matriks untuk [A|b] : 
[[ 6 -4 -2 20]
 [-4 18 -8  0]
 [-2 -8 15  0]]

 ====================== PENYELESAIAN DENGAN GAUSS-NAIVE ===================== 

Untuk kolom ke-1 baris ke-2 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [-2.         -8.         15.          0.        ]] 

Untuk kolom ke-1 baris ke-3 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [ 0.         -9.33333333 14.33333333  6.66666667]] 

Untuk kolom ke-2 baris ke-3 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [ 0.          0.          8.65217391 14.7826087 ]] 


Didapat Akar Solusi Persam

#**GAUSS - JORDAN**

#**MATRIKS BALIKAN**

#**DEKOMPOSISI LU**