#**PROJECT-1 PRAKTIKUM FISIKA KOMPUTASI 118**

---
***Currents and Voltages in Resistor Circuits***
---

**KELOMPOK 2 - Fisika B**
1.   Dhinar Hidayath 		       (1306621054)
2.   Khansa Farras Callista	A. (1306621067)
3.   Puspa Zuhrotul Kamilah	   (1306621058)
4.   Salma Mardhiyah     	     (1306621061)



#**ELIMINASI GAUSS**

In [ ]:
def eliminasi_gauss(Ab):
    Ab = Ab.astype(float)
    print("\n", "="*22, "PENYELESAIAN DENGAN ELIMINASI GAUSS","="*21, "\n")

    for i in range(n):
        if np.fabs(Ab[0, 0]) < 1.0e-10:
            print('Divide by zero detected!\n')
            return
            
        for j in range(i+1, n):
            faktor = Ab[j][i]/Ab[i][i]
            for k in range(n+1):
                Ab[j][k] = Ab[j][k] - faktor * Ab[i][k]
            print("Untuk kolom ke-{} baris ke-{} :".format(i+1, j+1))
            print(Ab, "\n")
        
    # Back Substitution
    x[n-1] = Ab[n-1][n]/Ab[n-1][n-1]
    for i in range(n-2, -1, -1):
        sum = Ab[i][n]
        
        for j in range(i+1, n):
            sum = sum - Ab[i,j] * x[j]
        x[i] = sum/Ab[i][i]

    print("="*77)
    print("\nDidapat Akar Solusi Persamaan \nI1 = {} A\nI2 = {} A\nI3 = {} A\n".format(x[0], x[1], x[-1]))

    stop = timeit.default_timer()
    print('Running Time : ', stop - start, 'detik')
    return 

import numpy as np
import timeit

start = timeit.default_timer()

# Judul Program
print("======= MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE ELIMINASI GAUSS =======\n")

# Matriks yang digunakan
print("Sistem Persamaan Linear \n-6I1 - 4I2 - 2I3  = 20 \n-4I1 + 18I2 - 8I3 = 0 \n-2I1 - 8I2 + 15I3 = 0")

A = np.array([[6,-4,-2], [-4,18,-8], [-2,-8,15]])
b = np.array([20, 0, 0])
n = len(b)
x = np.zeros(n)
Ab = np.column_stack((A, b))

print(f"\nMatriks A : \n{A}\n\nMatriks b :  \n{np.transpose([b])}")
print(f"\nMaka, matriks untuk [A|b] : \n{Ab}")

# Memanggil fungsi definisi eliminasi gauss
solusi = eliminasi_gauss(Ab)

# SELESAI

======= MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE ELIMINASI GAUSS =======

Sistem Persamaan Linear 
-6I1 - 4I2 - 2I3  = 20 
-4I1 + 18I2 - 8I3 = 0 
-2I1 - 8I2 + 15I3 = 0

Matriks A : 
[[ 6 -4 -2]
 [-4 18 -8]
 [-2 -8 15]]

Matriks b :  
[[20]
 [ 0]
 [ 0]]

Maka, matriks untuk [A|b] : 
[[ 6 -4 -2 20]
 [-4 18 -8  0]
 [-2 -8 15  0]]

 ====================== PENYELESAIAN DENGAN ELIMINASI GAUSS ===================== 

Untuk kolom ke-1 baris ke-2 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [-2.         -8.         15.          0.        ]] 

Untuk kolom ke-1 baris ke-3 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [ 0.         -9.33333333 14.33333333  6.66666667]] 

Untuk kolom ke-2 baris ke-3 :
[[ 6.         -4.         -2.         20.        ]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [ 0.          0.          8.65217391 14.7826087 ]] 


Didapat Akar Solus

#**GAUSS - JORDAN**

In [ ]:
# Mendefinisikan Augmented Matriks dan Gauss Jordan

def gauss_jordan(Ab):
    
    print("\n", "="*17, "PENYELESAIAN DENGAN METODE GAUSS-JORDAN","="*18, "\n")
    for i in range(n):
        if np.fabs(Ab[i, i]) < 1.0e-10:
            print('Divide by zero detected!\n')
            return
        
        # Pivoting
        pivot = Ab[i, i]
        Ab[i, :] = Ab[i, :]/pivot
        print("{} [Pivot = {:.4f}] {}\n".format("-"*24, pivot, "-"*28))
        print(f"Membuat matriks diagonal 1 pada {i} dengan pivot \n{Ab}\n")

        # Eliminasi
        for k in range (n):
            if k == i or Ab[k, i] == 0: 
                continue
            faktor = Ab[k, i]
            Ab[k,:] = Ab[k, :] - faktor * Ab[i, :]
            print(f"Untuk kolom ke-{i+1} baris ke-{k+1} : \n{Ab}\n")
    
    print("="*97)
    print(f"\nMaka, didapat untuk nilai kuat arus (I) dari rangkaian listrik DC 3 loop degan 3 variabel ialah \nI1 = {Ab[0, 3]:} A \nI2 = {Ab[1, 3]:} A \nI3 = {Ab[2, 3]:} A\n")
    stop = timeit.default_timer()
    print("Running Time :", stop - start,'s')
    return 

import numpy as np
import timeit

start = timeit.default_timer()

# Judul Program
print("="*9, "MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE ELIMINASI GAUSS-JORDAN", "="*10, "\n")

# Matriks yang digunakan
print("Sistem Persamaan Linear \n6I1 - 4I2 -2I3 = 20 \n-4I1 + 18I2 + -8I3 = 0 \n-2I1 - 8I2 + 15I3  = 0")

A = np.array([[  6,   -4,   -2],
              [ -4,   18,   -8],
              [ -2,   -8,    15]], float)
b = np.array([20, 0, 0], float)


#Augmented
Ab = np.column_stack((A, b))
print(f"\nMatriks A : \n{A} \n\nMatriks b : \n{np.transpose([b])}")
print(f"\nMaka, matriks untuk [A|b] : \n{Ab}")

# Memanggil fungsi definisi Gauss Jordan
n = len(b)
X = gauss_jordan(Ab)

# SELESAI

========= MENCARI ARUS PADA RANGKAIAN LISTRIK DENGAN METODE ELIMINASI GAUSS-JORDAN ========== 

Sistem Persamaan Linear 
6I1 - 4I2 -2I3 = 20 
-4I1 + 18I2 + -8I3 = 0 
-2I1 - 8I2 + 15I3  = 0

Matriks A : 
[[ 6. -4. -2.]
 [-4. 18. -8.]
 [-2. -8. 15.]] 

Matriks b : 
[[20.]
 [ 0.]
 [ 0.]]

Maka, matriks untuk [A|b] : 
[[ 6. -4. -2. 20.]
 [-4. 18. -8.  0.]
 [-2. -8. 15.  0.]]

 ================= PENYELESAIAN DENGAN METODE GAUSS-JORDAN ================== 

------------------------ [Pivot = 6.0000] ----------------------------

Membuat matriks diagonal 1 pada 0 dengan pivot 
[[ 1.         -0.66666667 -0.33333333  3.33333333]
 [-4.         18.         -8.          0.        ]
 [-2.         -8.         15.          0.        ]]

Untuk kolom ke-1 baris ke-2 : 
[[ 1.         -0.66666667 -0.33333333  3.33333333]
 [ 0.         15.33333333 -9.33333333 13.33333333]
 [-2.         -8.         15.          0.        ]]

Untuk kolom ke-1 baris ke-3 : 
[[ 1.         -0.66666667 -0.33333333  3.33333333]
 [

#**MATRIKS BALIKAN**

In [ ]:
#Mencetak judul program
print('Mencari Arus Pada Rangkaian Listrik DC 3 Loop Menggunakan Metode Matriks Balikan')

#Mengimport modul yang dibutuhkan
import numpy as np
import timeit

start = timeit.default_timer()
#Membuat fungsi yang akan digunakan pada program utama 
def decomposition_LU(A):
  n = len(A)
  Lower = [[0 for x in range(n)]
           for y in range(n)]
  Upper = [[0 for x in range(n)]
           for y in range(n)]
  
  #forward substitution
def forward_substitution(b,Lower):
  n = len(b)
  forward = [[0 for x in range(n)]
              for y in range(n)]
  
  for i in range(n): 
    sum = 0
    for j in range(i):
      sum = sum + Lower[i][j]*forward[j] 
    forward[i] = b[i] - sum
    
  return forward
  
  #backward substitution
def backward_substitution(forward,Upper):
  n = len(forward)
  backward = [[0 for x in range(n)]
            for y in range(n)]

  for i in range(n,0,-1):
    sum = 0
    for j in range(i,n):
      sum = sum + Upper[i-1][j]*backward[j]
    a = 1
    b = (Upper[i-1][i-1])*(forward[i-1]-sum)
    backward[i-1] = (a/b) if b != 0 else 0 
   
  return backward

#Membuat variabel untuk menyatakan matriks
A = np.array([[6, -4, -2], [-4, 18, -8], [-2, -8, 15]])
b = np.array([[20], [0], [0]])

#Mencetak matriks A dan b
print(f'\nMatriks A = \n{A}')
print(f'\nMatriks b = \n{b}')

#membuat program untuk mencari matriks balikan dan solusi l1, l2, l3
decomposition = decomposition_LU(A)
n = len(A)
Lower = [[0 for x in range(n)]
           for y in range(n)]
Upper = [[0 for x in range(n)]
           for y in range(n)]

forward = forward_substitution(b,Lower)
print("\nHasil dari forward substitution") 
for i in range(0,3):
  print('f%d : %.2f' %(i+1,forward[i]))

backward = backward_substitution(forward,Upper)
print("\nHasil dari backward substitution")
for i in range(0,3):
  print('X%d : %.2f' %(i+1,backward[i]))

inverse = np.linalg.inv(A)
inverse
np.round(inverse @ A)
print(f'\nHasil dari Matriks Balikan adalah \n{inverse}')

solusi = np.linalg.solve(A,b)
print(f'\nMaka, \nsolusi untuk i1 adalah {solusi[0]} A')
print(f'solusi untuk i2 adalah {solusi[1]} A')
print(f'solusi untuk i3 adalah {solusi[2]} A')

stop = timeit.default_timer()
print('Running Time : ', stop - start)

Mencari Arus Pada Rangkaian Listrik DC 3 Loop Menggunakan Metode Matriks Balikan

Matriks A = 
[[ 6 -4 -2]
 [-4 18 -8]
 [-2 -8 15]]

Matriks b = 
[[20]
 [ 0]
 [ 0]]

Hasil dari forward substitution
f1 : 20.00
f2 : 0.00
f3 : 0.00

Hasil dari backward substitution
X1 : 0.00
X2 : 0.00
X3 : 0.00

Hasil dari Matriks Balikan adalah 
[[0.25879397 0.09547739 0.08542714]
 [0.09547739 0.1080402  0.07035176]
 [0.08542714 0.07035176 0.11557789]]

Maka, 
solusi untuk i1 adalah [5.1758794] A
solusi untuk i2 adalah [1.90954774] A
solusi untuk i3 adalah [1.70854271] A
Running Time :  0.0324464039999981


#**DEKOMPOSISI LU**

In [ ]:
#fungsi dekomposisi LU
def decomposition_LU(A):
  #menyesuaikan dengan panjang matriks
  n = len(A)

  # menolkan matriks L dan U
  Lower = [[0 for x in range(n)]
           for y in range(n)]
  Upper = [[0 for x in range(n)]
           for y in range(n)]
  
  #membuat looping
  for i in range(n):
    #  matrix Upper
    for j in range(i,n):
      # jumlah dari Lower[i][k]*Upper[k][j]
      jumlah = 0
      for k in range(i):
        a = Lower[i][k]*Upper[k][j]
        jumlah = round(jumlah + a,2)
      #mengevaluasi Upper[i][j]
      Upper[i][j] = A[i][j] - jumlah

    # Matriks Lower
    for j in range (i,n):
      if (i==j):
        # Membuat diagonal matriks L = 1
        Lower[i][i]=1
      else:
        # jumlah dari Lower[j][k]*Upper[k][i]
        jumlah = 0
        for k in range(i):
          d = Lower[j][k]*Upper[k][i]
          jumlah = jumlah + d
        #mengevaluasi ower[j][i]
        c = A[j][i] - jumlah
        Lower[j][i] = round(c/Upper[i][i],2)

  return Lower, Upper

#fungsi substitusi forward
def forward_substitution(b,Lower):
  #menyesuaikan dengan panjang matriks B
  n = len(B)
  #menolkan matriks substitusi forward
  forward = [[0 for x in range(n)]
             for y in range(n)]

  for i in range(n):
    #jumlah dari Lower[i][j]*forward[j] 
    jumlah = 0
    for j in range(i):
      jumlah = jumlah + Lower[i][j]*forward[j] 
    #mengevaluasi matriks substitusi forward
    forward[i] = B[i] - jumlah
    
  return forward

# fungsi substitusi backward
def backward_substitution(forward,Upper):
  #menyesuaikan dengan panjang matriks substitusi forward
  n = len(forward)
  #menolkan matriks substitusi backward
  backward = [[0 for x in range(n)]
              for y in range(n)]

  for i in range(n,0,-1):
    #jumlah dari Upper[i-1][j]*backward[j]
    jumlah = 0
    for j in range(i,n):
      jumlah = jumlah + Upper[i-1][j]*backward[j]  
    #mengevaluasi matriks substitusi backward
    backward[i-1] = (1/Upper[i-1][i-1])*(forward[i-1]-jumlah)
   
  return backward


import numpy 
from numpy import array
import timeit

# mendefinisikan start sebagai waktu awal
start = timeit.default_timer()

# mencetak Judul dan Identitas Kelompok
print("Project-1_Team 2_FB_Currents And Voltages In Resistor Circuits")
print("Praktikum Fisika Komputasi 118")
print("Dhinar Hidayath             (1306621054)")
print("Khansa Farras Callista A.   (1306621067)")
print("Puspa Zuhrotul Kamilah      (1306621058)")
print("Salma Mardhiyah             (1306621061)\n")
print("="*22, "Dekomposisi LU", "="*23, "\n")

# matrix A
A = array ([[6.0, -4.0, -2.0], 
     [-4.0, 18, -8.0], 
     [-2.0, -8.0, 15]])

# matriks B
B = [20, 0.0, 0.0]

# mencetak matriks A dan B
print("matriks A: \n",A)
print("\nmatriks B: \n",B)

# Menghitung matriks L dan U dengan memanggil fungsi dekomposisi LU    
# dan mendefinsiikannya dengan Lower dan Upper
Lower, Upper = decomposition_LU(A)

# menyesuaikan dengan panjang matriks A
n = len(A)

# mencetak penamaan matriks L dan U
print("\nMatriks L (lower)\t\tMatriks U (upper)")

# membuat pengulangan
for i in range(n):
  # mencetak matriks Lower (L)
  for j in range(n):
    print(Lower[i][j], end="\t")
  print("", end="\t")
 
  # mencetak matriks Upper (U)
  for j in range(n):
    print(Upper[i][j], end="\t")
  print("")

# memanggil fungsi substitusi forward
# kemudian memasukan matriks B dan Lower ke dalam fungsi
# dan mendefinisikannya dengan forward
forward = forward_substitution(B,Lower)

# mencetak penamaan hasil dari substitusi forward 
print("\nHasil dari forward substitution")
# mencetak hasil dari substitusi forward 
for i in range(0,3):
  print('D%d : %.2f' %(i+1,forward[i]))

# memanggik fungsi substitusi backward
# kemudian memasukkan forward dan Upper ke dalam fungsi
# dan mendefinisikannya dengan backward
backward = backward_substitution(forward,Upper)

# mencetak penamaan hasil dari substitusi backward
print("\nHasil dari backward substitution")
# mencetak hasil dari substitusi backward
for i in range(0,3):
  print('X%d : %.2f' %(i+1,backward[i]))

# mendefinisikan stop sebagai waktu akhir
stop = timeit.default_timer()

# mencetak runnung time
print('\nWaktu prose berjalan : ', stop - start, 'detik')

Project-1_Team 2_FB_Currents And Voltages In Resistor Circuits
Praktikum Fisika Komputasi 118
Dhinar Hidayath             (1306621054)
Khansa Farras Callista A.   (1306621067)
Puspa Zuhrotul Kamilah      (1306621058)
Salma Mardhiyah             (1306621061)

====================== Dekomposisi LU ======================= 

matriks A: 
 [[ 6. -4. -2.]
 [-4. 18. -8.]
 [-2. -8. 15.]]

matriks B: 
 [20, 0.0, 0.0]

Matriks L (lower)		Matriks U (upper)
1	0	0		6.0	-4.0	-2.0	
-0.67	1	0		0	15.32	-9.34	
-0.33	-0.61	1		0	0	8.64	

Hasil dari forward substitution
D1 : 20.00
D2 : 13.40
D3 : 14.77

Hasil dari backward substitution
X1 : 5.18
X2 : 1.92
X3 : 1.71

Waktu prose berjalan :  0.01649507900003755 detik
